version: '3'
services:
  eureka:
    image: "discoveryserver:2.0.0-SNAPSHOT"
    hostname: "localhost"
    ports:
     - "8761:8761"

  employee-salary-service:
    image: "employee-salary-service:2.0.0-SNAPSHOT"
    hostname: "localhost"
    links:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8183:8183"

  employee-info-service:
    image: "employee-info-service:2.0.0-SNAPSHOT"
    hostname: "localhost"
    links:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8184:8184"
      
  employee-details-service:
    image: "employee-details-service:2.0.0-SNAPSHOT"
    hostname: "localhost"
    links:
      - eureka
      - employee-salary-service
      - employee-info-service
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8182:8181"
      
  hystrix-service:
    image: "hystrix:2.0.0-SNAPSHOT"
    hostname: "localhost"
    links:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8091:8090"
