version: '3'
services:
  eureka:
    image: "discoveryserver:2.0.0-SNAPSHOT"
    hostname: "localhost"
    ports:
     - "8761:8761"
     
  #config-server:
    #image: "config-server:2.0.0-SNAPSHOT"
    #hostname: "localhost"
    #ports:
    # - "8888:8888"
  mysql:
    image: mysql
    container_name: mysqlDB
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=employeeDB
      - MYSQL_USER=emp
      - MYSQL_PASSWORD=emp
    hostname: "localhost"
    ports:
      - "4406:4406"
    restart: always  
    volumes:
      - /data:/docker-entrypoint-initdb.d

  employee-salary-service:
    image: "employee-salary-service:2.0.0-SNAPSHOT"
    hostname: "localhost"
    links:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8183:8183"

  employee-info-service:
    image: "employee-info-service:2.0.0-SNAPSHOT"
    hostname: "localhost"
    links:
      - eureka
      - mysql
      #- config-server
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8184:8184"
      
  employee-details-service:
    image: "employee-details-service:2.0.0-SNAPSHOT"
    hostname: "localhost"
    links:
      - eureka
      - employee-salary-service
      - employee-info-service
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8182:8181"
      
  hystrix-service:
    image: "hystrix:2.0.0-SNAPSHOT"
    hostname: "localhost"
    links:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8091:8090"
