version: '3'
services:
  eureka:
    #image: "discoveryserver:2.0.0-SNAPSHOT"
    build: ./discoveryServer
    image: eureka
    container_name: eureka
    hostname: "localhost"
    networks:
     - microservice-docker
    ports:
     - "8761:8761"
     
  config-server:
    build: ./configserver
    image: configserver
    container_name: config-server
    hostname: "localhost"
    networks:
     - microservice-docker
    ports:
      - "8888:8888"
     
  zipkin-service:
    image: openzipkin/zipkin
    container_name: zipkin
    hostname: "localhost"
    networks:
     - microservice-docker
    ports:
      - "9411:9411"
     
  mysql:
    image: mysql
    container_name: mysqlDB
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=employeeDB
      - MYSQL_USER=emp
      - MYSQL_PASSWORD=emp
    hostname: "localhost"
    networks:
     - microservice-docker
    ports:
      - "4406:4406"
    restart: always  
    volumes:
      - amx-data:/var/lib/mysql

  employee-salary-service:
    #image: "employee-salary-service:2.0.0-SNAPSHOT"
    build: ./employee-salary-service
    image: employee-salary-service
    container_name: employee-salary-service
    hostname: "employee-salary-service"
    networks:
     - microservice-docker
    links:
      - eureka
    depends_on:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8183:8183"

  employee-info-service:
    #image: "employee-info-service:2.0.0-SNAPSHOT"
    build: ./employee-info-service
    image: employee-info-service
    container_name: employee-info-service
    hostname: "employee-info-service"
    networks:
     - microservice-docker
    links:
      - eureka
      - mysql
      #- config-server
    depends_on:
      - mysql
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8184:8184"
      
  employee-details-service:
    #image: "employee-details-service:2.0.0-SNAPSHOT"
    build: ./employee-details-service
    image: employee-details-service
    container_name: employee-details-service
    hostname: "employee-details-service"
    networks:
     - microservice-docker
    links:
      - eureka
      - employee-salary-service
      - employee-info-service
    depends_on:
      - eureka
      - config-server
      - zipkin-service
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8181:8181"
      
  hystrix-service:
    #image: "hystrix:2.0.0-SNAPSHOT"
    build: ./hystrix
    image: hystrix
    container_name: hystrix
    hostname: "localhost"
    networks:
     - microservice-docker
    links:
      - eureka
    depends_on:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8091:8090"

networks:
  microservice-docker:
volumes:
  amx-data: