version: '3'
services:
  eureka:
    #image: "discoveryserver:2.0.0-SNAPSHOT"
    build: ./discoveryServer
    hostname: "IN-00207677"
    networks:
     - microservice-docker
    ports:
     - "8761:8761"
     
  #config-server:
    #image: "config-server:2.0.0-SNAPSHOT"
    #hostname: "IN-00207677"
    #ports:
    # - "8888:8888"
  mysql:
    image: mysql
    container_name: mysqlDB
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=employeeDB
      - MYSQL_USER=emp
      - MYSQL_PASSWORD=emp
    hostname: "IN-00207677"
    networks:
     - microservice-docker
    ports:
      - "4406:4406"
    restart: always  
    volumes:
      - amx-data:/var/lib/mysql

  employee-salary-service:
    #image: "employee-salary-service:2.0.0-SNAPSHOT"
    build: ./employee-salary-service
    hostname: "IN-00207677"
    networks:
     - microservice-docker
    links:
      - eureka
    depends_on:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8183:8183"

  employee-info-service:
    #image: "employee-info-service:2.0.0-SNAPSHOT"
    build: ./employee-info-service
    hostname: "IN-00207677"
    networks:
     - microservice-docker
    links:
      - eureka
      - mysql
      #- config-server
    depends_on:
      - mysql
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8184:8184"
      
  employee-details-service:
    #image: "employee-details-service:2.0.0-SNAPSHOT"
    build: ./employee-details-service
    hostname: "IN-00207677"
    networks:
     - microservice-docker
    links:
      - eureka
      - employee-salary-service
      - employee-info-service
    depends_on:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8181:8181"
      
  hystrix-service:
    #image: "hystrix:2.0.0-SNAPSHOT"
    build: ./hystrix
    hostname: "IN-00207677"
    networks:
     - microservice-docker
    links:
      - eureka
    depends_on:
      - eureka
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "8091:8090"
networks:
  microservice-docker:
volumes:
  amx-data: