spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: employee-details-service
          uri: lb://employee-details-service
          predicates:
            - Path=/details/**
          filters:
            - name: CircuitBreaker
              args:
                name: employee-details-service
                fallbackuri: forward:/empDeatilsFallBack
        #- id: payment-service
          #uri: lb://PAYMENT-SERVICE
          #predicates:
            #- Path=/payment/**
          #filters:
            #- name: CircuitBreaker
              #args:
               # name: payment-service
                #fallbackuri: forward:/paymentFallback
                

server:
  port: 8989
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  
