spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: employee-details-service
          uri: lb://employee-details-service
          predicates:
            - Path=/empdetails/**
          filters:
            - name: CircuitBreaker
              args:
                name: employee-details-service
                fallbackuri: forward:/empDeatilsFallBack
                
        - id: employee-details-service
          uri: lb://employee-details-service
          predicates:
            - Path=/emptest/**
                
        - id: employee-info-service
          uri: lb://employee-info-service
          predicates:
            - Path=/empinfo/**
          filters:
            - name: CircuitBreaker
              args:
                name: employee-info-service
                fallbackuri: forward:/empInfoFallBack
                
        - id: employee-salary-service
          uri: lb://employee-salary-service
          predicates:
            - Path=/empsalary/**
          filters:
            - name: CircuitBreaker
              args:
                name: employee-salary-service
                fallbackuri: forward:/empSalaryFallBack
                
        - id: employee-kafka-consumer
          uri: lb://employee-kafka-consumer
          predicates:
            - Path=/empkafka/**  
                

server:
  port: 8989
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  
